// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: productService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductService interface {
	GetProductsList(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductsListResponse, error)
	GetProduct(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductDetailResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "services"
	}
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) GetProductsList(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductsListResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.GetProductsList", in)
	out := new(ProductsListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetProduct(ctx context.Context, in *ProductRequest, opts ...client.CallOption) (*ProductDetailResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.GetProduct", in)
	out := new(ProductDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	GetProductsList(context.Context, *ProductRequest, *ProductsListResponse) error
	GetProduct(context.Context, *ProductRequest, *ProductDetailResponse) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productService interface {
		GetProductsList(ctx context.Context, in *ProductRequest, out *ProductsListResponse) error
		GetProduct(ctx context.Context, in *ProductRequest, out *ProductDetailResponse) error
	}
	type ProductService struct {
		productService
	}
	h := &productServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandler struct {
	ProductServiceHandler
}

func (h *productServiceHandler) GetProductsList(ctx context.Context, in *ProductRequest, out *ProductsListResponse) error {
	return h.ProductServiceHandler.GetProductsList(ctx, in, out)
}

func (h *productServiceHandler) GetProduct(ctx context.Context, in *ProductRequest, out *ProductDetailResponse) error {
	return h.ProductServiceHandler.GetProduct(ctx, in, out)
}
