// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: otherService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CarouselRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"carousel_id" form:"carousel_id" uri:"carousel_id"
	CarouselID uint32 `protobuf:"varint,1,opt,name=carouselID,proto3" json:"carouselID,omitempty"`
	// @inject_tag: json:"product_id" form:"product_id" uri:"product_id"
	ProductID uint32 `protobuf:"varint,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	// @inject_tag: json:"img_path" form:"img_path" uri:"img_path"
	ImgPath string `protobuf:"bytes,3,opt,name=ImgPath,proto3" json:"ImgPath,omitempty"`
}

func (x *CarouselRequest) Reset() {
	*x = CarouselRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otherService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarouselRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarouselRequest) ProtoMessage() {}

func (x *CarouselRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otherService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarouselRequest.ProtoReflect.Descriptor instead.
func (*CarouselRequest) Descriptor() ([]byte, []int) {
	return file_otherService_proto_rawDescGZIP(), []int{0}
}

func (x *CarouselRequest) GetCarouselID() uint32 {
	if x != nil {
		return x.CarouselID
	}
	return 0
}

func (x *CarouselRequest) GetProductID() uint32 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *CarouselRequest) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

type CarouselsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarouselsList []*CarouselModel `protobuf:"bytes,1,rep,name=CarouselsList,proto3" json:"CarouselsList,omitempty"`
}

func (x *CarouselsListResponse) Reset() {
	*x = CarouselsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otherService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarouselsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarouselsListResponse) ProtoMessage() {}

func (x *CarouselsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otherService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarouselsListResponse.ProtoReflect.Descriptor instead.
func (*CarouselsListResponse) Descriptor() ([]byte, []int) {
	return file_otherService_proto_rawDescGZIP(), []int{1}
}

func (x *CarouselsListResponse) GetCarouselsList() []*CarouselModel {
	if x != nil {
		return x.CarouselsList
	}
	return nil
}

type CarouselDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarouselDetail *CarouselModel `protobuf:"bytes,1,opt,name=CarouselDetail,proto3" json:"CarouselDetail,omitempty"`
}

func (x *CarouselDetailResponse) Reset() {
	*x = CarouselDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otherService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarouselDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarouselDetailResponse) ProtoMessage() {}

func (x *CarouselDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otherService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarouselDetailResponse.ProtoReflect.Descriptor instead.
func (*CarouselDetailResponse) Descriptor() ([]byte, []int) {
	return file_otherService_proto_rawDescGZIP(), []int{2}
}

func (x *CarouselDetailResponse) GetCarouselDetail() *CarouselModel {
	if x != nil {
		return x.CarouselDetail
	}
	return nil
}

var File_otherService_proto protoreflect.FileDescriptor

var file_otherService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x14,
	0x63, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x6f, 0x75,
	0x73, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x72,
	0x6f, 0x75, 0x73, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x49, 0x6d, 0x67, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x56, 0x0a, 0x15, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x6f,
	0x75, 0x73, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x6f, 0x75,
	0x73, 0x65, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0d, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73,
	0x65, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x16, 0x43, 0x61, 0x72, 0x6f, 0x75,
	0x73, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x0e, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x32, 0xad, 0x01, 0x0a, 0x0c, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73,
	0x65, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x61,
	0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72,
	0x6f, 0x75, 0x73, 0x65, 0x6c, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x43, 0x61, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x6f,
	0x75, 0x73, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otherService_proto_rawDescOnce sync.Once
	file_otherService_proto_rawDescData = file_otherService_proto_rawDesc
)

func file_otherService_proto_rawDescGZIP() []byte {
	file_otherService_proto_rawDescOnce.Do(func() {
		file_otherService_proto_rawDescData = protoimpl.X.CompressGZIP(file_otherService_proto_rawDescData)
	})
	return file_otherService_proto_rawDescData
}

var file_otherService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_otherService_proto_goTypes = []interface{}{
	(*CarouselRequest)(nil),        // 0: services.CarouselRequest
	(*CarouselsListResponse)(nil),  // 1: services.CarouselsListResponse
	(*CarouselDetailResponse)(nil), // 2: services.CarouselDetailResponse
	(*CarouselModel)(nil),          // 3: services.CarouselModel
}
var file_otherService_proto_depIdxs = []int32{
	3, // 0: services.CarouselsListResponse.CarouselsList:type_name -> services.CarouselModel
	3, // 1: services.CarouselDetailResponse.CarouselDetail:type_name -> services.CarouselModel
	0, // 2: services.OtherService.GetCarouselsList:input_type -> services.CarouselRequest
	0, // 3: services.OtherService.UpdateCarousel:input_type -> services.CarouselRequest
	1, // 4: services.OtherService.GetCarouselsList:output_type -> services.CarouselsListResponse
	2, // 5: services.OtherService.UpdateCarousel:output_type -> services.CarouselDetailResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_otherService_proto_init() }
func file_otherService_proto_init() {
	if File_otherService_proto != nil {
		return
	}
	file_carouselModels_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_otherService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarouselRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otherService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarouselsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otherService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarouselDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otherService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otherService_proto_goTypes,
		DependencyIndexes: file_otherService_proto_depIdxs,
		MessageInfos:      file_otherService_proto_msgTypes,
	}.Build()
	File_otherService_proto = out.File
	file_otherService_proto_rawDesc = nil
	file_otherService_proto_goTypes = nil
	file_otherService_proto_depIdxs = nil
}
